.PHONY: all clean
all:
$(OBJECTS)/update:
	$(MKDIR) -p $@
$(OBJECTS)/update/annul.o: src/update/annul.c $(OBJECTS)/update
	$(CC) $(CFLAGS) -c -o $@ $<
$(OBJECTS)/update/apply.o: src/update/apply.c $(OBJECTS)/update
	$(CC) $(CFLAGS) -c -o $@ $<
$(OBJECTS)/update/check.o: src/update/check.c $(OBJECTS)/update
	$(CC) $(CFLAGS) -c -o $@ $<
$(OBJECTS)/update/fetch.o: src/update/fetch.c $(OBJECTS)/update
	$(CC) $(CFLAGS) -c -o $@ $<
$(OBJECTS)/update/main.o: src/update/main.c $(OBJECTS)/update
	$(CC) $(CFLAGS) -c -o $@ $<
$(OBJECTS)/update/set.o: src/update/set.c $(OBJECTS)/update
	$(CC) $(CFLAGS) -c -o $@ $<
$(OBJECTS)/update/state.o: src/update/state.c $(OBJECTS)/update
	$(CC) $(CFLAGS) -c -o $@ $<
$(BINARIES)/update: $(OBJECTS)/update/annul.o $(OBJECTS)/update/apply.o $(OBJECTS)/update/check.o $(OBJECTS)/update/fetch.o $(OBJECTS)/update/main.o $(OBJECTS)/update/set.o $(OBJECTS)/update/state.o
	$(LD) $(LDFLAGS) $(UPDATEFLAGS) -o $@ $^
all: $(BINARIES)/update
clean:
	rm -rf $(BINARIES)/* $(LIBRARIES)/* $(OBJECTS)/*
